version: '3'

services:
  front:
    build:
      context: ./AlocaCarFront  # Caminho para o Dockerfile do front
    container_name: front
    ports:
      - "80:80"
    volumes:
      - ./AlocaCarFront:/home/node/app  # Ajuste para o caminho do seu código front

  api:
    build:
      context: ./API_Locadora  # Caminho para o Dockerfile da API
    container_name: api
    ports:
      - "443:443"
    volumes:
      - ./API_Locadora:/home/node/app  # Ajuste para o caminho do seu código da API

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
