version: '3'

services:
  front:
    build:
      context: ./AlocaCarFront  # Caminho para o Dockerfile do front
    container_name: front
    ports:
      - "80:80"
    volumes:
      - ./AlocaCarFront:/home/node/app  # Ajuste para o caminho do seu código front

  api:
    build:
      context: ./API_Locadora  # Caminho para o Dockerfile da API
    container_name: api
    ports:
      - "443:443"
    volumes:
      - ./API_Locadora:/home/node/app  # Ajuste para o caminho do seu código da API

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./dados_mongo:/data/db
